name: Profile Views Counter

on:
  workflow_dispatch:
  page_build:
  schedule:
    - cron: '0 * * * *' # Runs every hour

  push:
    branches:
      - main

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read and update view count
        run: |
          FILE=views.json

          if [ -f "$FILE" ]; then
            COUNT=$(jq -r '.message' $FILE)  # Extract the view count as a string
            COUNT=$((COUNT + 1))  # Convert to integer and increment
          else
            COUNT=1
          fi

          # Generate Shields.io JSON format
          jq -n --arg label "Profile Views" --arg message "$COUNT" --arg color "blue" \
            '{schemaVersion: 1, label: $label, message: ($message | tostring), color: $color}' > $FILE

      - name: Commit and push changes
        run: |
          git config --global user.name "James Cao"
          git config --global user.email "caohoangphuc2909@gmail.com"

          # Set Timezone to UTC+7 for Commit Message
          export TZ="Asia/Bangkok"
          DATE=$(date +"%Y-%m-%d %H:%M:%S %Z")

          git add views.json
          git commit -m "Profile view recorded on $DATE (UTC+7)" || exit 0
          git push
